[build]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"
  # Increase memory limit for Node.js
  NODE_OPTIONS = "--max_old_space_size=4096"

# Use the Next.js Runtime
[functions]
  # This will be used for the Next.js functions
  directory = ".netlify/functions-internal"
  # Increase the function timeout
  node_bundler = "esbuild"

# Optimize build caching
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

# Handle Next.js routes
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 