[build]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"
  # Increase memory limit for Node.js
  NODE_OPTIONS = "--max_old_space_size=4096"
  # Add Supabase environment variables
  NEXT_PUBLIC_SUPABASE_URL = "https://yvbwzbcxogwxvbymlmsj.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2Ynd6YmN4b2d3eHZieW1sbXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NDAwMjAsImV4cCI6MjA1NzMxNjAyMH0._GUA9qK5OmPe-DN_89UqHPncW7JcN36rcFjcjoNdVQg"
  # Add the exact variable names expected by the build process
  supabaseUrl = "https://yvbwzbcxogwxvbymlmsj.supabase.co"
  supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2Ynd6YmN4b2d3eHZieW1sbXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NDAwMjAsImV4cCI6MjA1NzMxNjAyMH0._GUA9qK5OmPe-DN_89UqHPncW7JcN36rcFjcjoNdVQg"

# Use the Next.js Runtime
[functions]
  # This will be used for the Next.js functions
  directory = ".netlify/functions-internal"
  # Increase the function timeout
  node_bundler = "esbuild"
  # Set a longer timeout for functions
  included_files = [".next/standalone/**", ".next/static/**"]

# Optimize build caching
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

# Configure build caching
[build.cache]
  # Enable build caching
  enable = true
  # Cache the Next.js build cache
  paths = [
    ".next/cache",
    "node_modules/.cache"
  ]

# Handle Next.js routes
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
  force = true

# Fallback for 404 errors - redirect to index
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 